### PR TITLE
Apple silicone support

### PR DESCRIPTION
**Pull request by segiddins**

### CODE REVIEW

**Comment by richdex14** [comment]
I'm trying to build this on MacOS Big Sur ARM64 Beta, and Using Ruby 2.7 installed via Homebrew. I am getting this error: 
```
Undefined symbols for architecture arm64:
  "_ffi_call", referenced from:
      _ffi_raw_call in raw_api.o
      _ffi_java_raw_call in java_raw_api.o
  "_ffi_prep_cif_machdep", referenced from:
      _ffi_prep_cif_core in prep_cif.o
  "_ffi_prep_cif_machdep_var", referenced from:
      _ffi_prep_cif_core in prep_cif.o
  "_ffi_prep_closure_loc", referenced from:
      _ffi_prep_raw_closure_loc in raw_api.o
      _ffi_prep_java_raw_closure_loc in java_raw_api.o
ld: symbol(s) not found for architecture arm64
```
Were you using a different config/Ruby version to get the tests to pass? I tried building with Rake as well as Gem and got the same result.

**Comment by segiddins** [comment]
I was building against system libffi

**Comment by richdex14** [comment]
Ah, I just tried this and you're right, after I installed libffi through Homebrew (they fixed that formula just 4 days ago!) it works now. Thanks!

**Comment by richdex14** [comment]
Hmm so it built correctly and I could run a basic test program, but running the tests with `rake test` still fails on the test for `callback_spec.rb` seemingly, with a segmentation fault. I can post the whole (massive) log if you want but here's what I think is the key part 
```
../usr/local/Cellar/ruby/2.7.1_2/lib/ruby/2.7.0/fiddle/import.rb:317: [BUG] Bus Error at 0x0000000100e10000
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [-darwin20]

-- Ruby level backtrace information ----------------------------------------
/usr/local/lib/ruby/gems/2.7.0/gems/rspec-core-3.9.2/exe/rspec:4:in `<main>'
/usr/local/lib/ruby/gems/2.7.0/gems/rspec-core-3.9.2/lib/rspec/core/runner.rb:45:in `invoke'
/usr/local/lib/ruby/gems/2.7.0/gems/rspec-core-3.9.2/lib/rspec/core/runner.rb:71:in `run'
/usr/local/lib/ruby/gems/2.7.0/gems/rspec-core-3.9.2/lib/rspec/core/runner.rb:89:in `run'
/usr/local/lib/ruby/gems/2.7.0/gems/rspec-core-3.9.2/lib/rspec/core/runner.rb:115:in `run_specs'
/usr/local/lib/ruby/gems/2.7.0/gems/rspec-core-3.9.2/lib/rspec/core/reporter.rb:74:in `report'
/usr/local/lib/ruby/gems/2.7.0/gems/rspec-core-3.9.2/lib/rspec/core/runner.rb:116:in `block in run_specs'
/usr/local/lib/ruby/gems/2.7.0/gems/rspec-core-3.9.2/lib/rspec/core/configuration.rb:2058:in `with_suite_hooks'
/usr/local/lib/ruby/gems/2.7.0/gems/rspec-core-3.9.2/lib/rspec/core/runner.rb:121:in `block (2 levels) in run_specs'
/usr/local/lib/ruby/gems/2.7.0/gems/rspec-core-3.9.2/lib/rspec/core/runner.rb:121:in `map'
/usr/local/lib/ruby/gems/2.7.0/gems/rspec-core-3.9.2/lib/rspec/core/runner.rb:121:in `block (3 levels) in run_specs'
/usr/local/lib/ruby/gems/2.7.0/gems/rspec-core-3.9.2/lib/rspec/core/example_group.rb:606:in `run'
/usr/local/lib/ruby/gems/2.7.0/gems/rspec-core-3.9.2/lib/rspec/core/example_group.rb:640:in `run_examples'
/usr/local/lib/ruby/gems/2.7.0/gems/rspec-core-3.9.2/lib/rspec/core/example_group.rb:640:in `map'
/usr/local/lib/ruby/gems/2.7.0/gems/rspec-core-3.9.2/lib/rspec/core/example_group.rb:644:in `block in run_examples'
/usr/local/lib/ruby/gems/2.7.0/gems/rspec-core-3.9.2/lib/rspec/core/example.rb:254:in `run'
/usr/local/lib/ruby/gems/2.7.0/gems/rspec-core-3.9.2/lib/rspec/core/example.rb:503:in `with_around_and_singleton_context_hooks'
/usr/local/lib/ruby/gems/2.7.0/gems/rspec-core-3.9.2/lib/rspec/core/example.rb:460:in `with_around_example_hooks'
/usr/local/lib/ruby/gems/2.7.0/gems/rspec-core-3.9.2/lib/rspec/core/hooks.rb:481:in `run'
/usr/local/lib/ruby/gems/2.7.0/gems/rspec-core-3.9.2/lib/rspec/core/hooks.rb:619:in `run_around_example_hooks_for'
/usr/local/lib/ruby/gems/2.7.0/gems/rspec-core-3.9.2/lib/rspec/core/hooks.rb:481:in `block in run'
/usr/local/lib/ruby/gems/2.7.0/gems/rspec-core-3.9.2/lib/rspec/core/example.rb:460:in `block in with_around_example_hooks'
/usr/local/lib/ruby/gems/2.7.0/gems/rspec-core-3.9.2/lib/rspec/core/example.rb:503:in `block in with_around_and_singleton_context_hooks'
/usr/local/lib/ruby/gems/2.7.0/gems/rspec-core-3.9.2/lib/rspec/core/example.rb:257:in `block in run'
/usr/local/lib/ruby/gems/2.7.0/gems/rspec-core-3.9.2/lib/rspec/core/example.rb:257:in `instance_exec'
/Users/dexterrichard/code/tools/ffi/spec/ffi/callback_spec.rb:855:in `block (2 levels) in <module:CallbackInteropSpecs>'
/Users/dexterrichard/code/tools/ffi/spec/ffi/callback_spec.rb:823:in `assert_callback_in_same_thread_called_once'
/Users/dexterrichard/code/tools/ffi/spec/ffi/callback_spec.rb:856:in `block (3 levels) in <module:CallbackInteropSpecs>'
/usr/local/Cellar/ruby/2.7.1_2/lib/ruby/2.7.0/fiddle/import.rb:317:in `bind_function'
/usr/local/Cellar/ruby/2.7.1_2/lib/ruby/2.7.0/fiddle/import.rb:317:in `new'
/usr/local/Cellar/ruby/2.7.1_2/lib/ruby/2.7.0/fiddle/import.rb:317:in `initialize'
```

**Comment by tmiw** [comment]
BTW, I use MacPorts and was having a really hard time using the system libffi, so I went ahead and adapted Homebrew's libffi fix to  libffi.darwin.mk to get the built-in libffi working too. That + updating built-in libffi to latest master + disabling custom trampoline seems to work with the changes in this PR. Should I create a separate PR for that or should it be included here?

FYI, the exact changes to libffi.darwin.mk are as follows:

```
diff --git a/ext/ffi_c/libffi b/ext/ffi_c/libffi
index ba480d9..45875da 160000
--- a/ext/ffi_c/libffi
+++ b/ext/ffi_c/libffi
@@ -1 +1 @@
-Subproject commit ba480d978b2205c0acb4c5a309088df836bcfc8c
+Subproject commit 45875da4bc71578f6f45471141c14e1743239b7e
diff --git a/ext/ffi_c/libffi.darwin.mk b/ext/ffi_c/libffi.darwin.mk
index 893a8e1..a7d72a5 100644
--- a/ext/ffi_c/libffi.darwin.mk
+++ b/ext/ffi_c/libffi.darwin.mk
@@ -23,6 +23,10 @@ ifneq ($(findstring -arch x86_64,$(ARCHFLAGS)),)
   ARCHES += x86_64
 endif
 
+ifneq ($(findstring -arch arm64,$(ARCHFLAGS)),)
+  ARCHES += arm64e
+endif
+
 ifeq ($(strip $(ARCHES)),)
 LIBFFI_BUILD_DIR = $(BUILD_DIR)/libffi-$(arch)
 # Just build the one (default) architecture
@@ -56,28 +60,32 @@ build_ffi = \
            echo "Configuring libffi for $(1)"; \
            cd "$(BUILD_DIR)"/libffi-$(1) && \
              env CC="$(CCACHE) $(CC)" CFLAGS="-arch $(1) $(LIBFFI_CFLAGS)" LDFLAGS="-arch $(1)" \
-               $(LIBFFI_CONFIGURE) --host=$(1)-apple-darwin > /dev/null; \
+               $(LIBFFI_CONFIGURE) --host=$(2)-apple-darwin > /dev/null; \
        fi); \
        $(MAKE) -C "$(BUILD_DIR)"/libffi-$(1)
 
-target_ffi = "$(BUILD_DIR)"/libffi-$(1)/.libs/libffi_convenience.a:; $(call build_ffi,$(1))
+target_ffi = "$(BUILD_DIR)"/libffi-$(1)/.libs/libffi_convenience.a:; $(call build_ffi,$(1),$(2))
 
 # Work out which arches we need to compile the lib for
 ifneq ($(findstring ppc,$(ARCHES)),)
-  $(call target_ffi,ppc)
+  $(call target_ffi,ppc,ppc)
 endif
 
 ifneq ($(findstring i386,$(ARCHES)),)
-  $(call target_ffi,i386)
+  $(call target_ffi,i386,i386)
 endif
 
 ifneq ($(findstring x86_64,$(ARCHES)),)
-  $(call target_ffi,x86_64)
+  $(call target_ffi,x86_64,x86_64)
+endif
+
+ifneq ($(findstring arm64e,$(ARCHES)),)
+  $(call target_ffi,arm64e,aarch64)
 endif
 
 
 $(LIBFFI):     $(LIBTARGETS)
-       # Assemble into a FAT (x86_64, i386, ppc) library
+       # Assemble into a FAT (x86_64, i386, ppc, arm64) library
        @mkdir -p "$(@D)"
        /usr/bin/libtool -static -o $@ \
            $(foreach arch, $(ARCHES),"$(BUILD_DIR)"/libffi-$(arch)/.libs/libffi_convenience.a)
@@ -90,6 +98,8 @@ $(LIBFFI):    $(LIBTARGETS)
                printf "#include \"libffi-x86_64/include/ffi.h\"\n";\
                printf "#elif defined(__ppc__)\n"; \
                printf "#include \"libffi-ppc/include/ffi.h\"\n";\
+               printf "#elif defined(__arm64__)\n"; \
+               printf "#include \"libffi-arm64e/include/ffi.h\"\n";\
                printf "#endif\n";\
        ) > "$(LIBFFI_BUILD_DIR)"/include/ffi.h
        @( \
@@ -99,6 +109,8 @@ $(LIBFFI):   $(LIBTARGETS)
                printf "#include \"libffi-x86_64/include/ffitarget.h\"\n";\
                printf "#elif defined(__ppc__)\n"; \
                printf "#include \"libffi-ppc/include/ffitarget.h\"\n";\
+               printf "#elif defined(__arm64__)\n"; \
+               printf "#include \"libffi-arm64e/include/ffitarget.h\"\n";\
                printf "#endif\n";\
        ) > "$(LIBFFI_BUILD_DIR)"/include/ffitarget.h
 
```

**Review by muratkalenderoglu — APPROVED** [review]

**Pull request closed without merging**
